version: "3"

services:

    nginx:
      image: nginx:latest
      container_name: nginx
      volumes:
        - ./nginx.dev.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80
        - 443:443
      depends_on:
        - server
        
    client:
        build:
          context: .
          dockerfile: Dockerfile.client
        image: ewanjones/client:latest
        working_dir: /app/
        command: bash -c "npm run dev"
        volumes:
            - node_modules:/app/node_modules/
            - ./client/:/app
        environment:
          - NODE_ENV=development
        ports:
          - "3000:3000"

    server:
        build:
          context: .
          dockerfile: Dockerfile.server
        image: ewanjones/server:latest
        working_dir: /app/
        command: bash -c "python manage.py runserver 0.0.0.0:9000"
        environment:
          - DJANGO_SETTINGS_MODULE=core.settings.development
        volumes:
            - ./server/:/app/
        ports:
          - "9000:9000"

volumes:
  node_modules:
