# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  run_tests:
    docker:
      # specify the version you desire here
      - image: circleci/python:3.7.7

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo/

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: pip install -r requirements.txt

      - save_cache:
          paths:
            - requirements.txt
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      - run: cd server && pytest

      # - store_test_results:
      #     path: tests
      #
      # - store_artifacts:
      #     path: tests
      #     destination: prefix


workflows:
  version: 2
  test:
    jobs:
      - run_tests
